### ISSUE TITLE
LibreCat doesn't work with version 0.0505 and higher

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/Catmandu-Store-Elasticsearch#15]
Start a current (as of today 0.5.3) installation LibreCat and try this:
```
bin/librecat user list 'lastname=e*'
*  1234                                     einstein             Einstein, Albert                         active    
count: 1
```
If you have other users on your system you should search for them.
Now try with a newer version:
```
rm -fr local/lib/perl5/Catmandu/Store/ElasticSearch*
cpanm -nl ./local Catmandu::Store::ElasticSearch@0.0505
``` 
And then again:
```
bin/librecat user list 'lastname=e*'
count: 0
```
So after Version 0.0504 somethings breaks.

**Comment by phochste** [comment]
LibreCat issues should best be posted in the LibreCat project where all the context on this project is available

**Comment by phochste** [comment]
Moved to https://github.com/LibreCat/LibreCat/issues/243
