### ISSUE TITLE
Add possibility to flush the bag without committing

### ISSUE THREAD

**Issue by EreMaijala** [LibreCat/Catmandu-Store-Elasticsearch#20]
Currently if you want to send the bag contents to Elasticsearch, you need to call commit or use the hacky `$store->bag->_bulk->flush;`. It would be nice to have a proper flush method that could be used to send the records to Elasticsearch without instructing it to commit them immediately.

**Comment by nics** [comment]
version 1.01 adds a flush method (which is also called before commit)
