### ISSUE TITLE
MARC -> Boolean values problem

### ISSUE THREAD

**Issue by tomascohen** [LibreCat/Catmandu-Store-Elasticsearch#22]
We are facing issues with MARC records being converted to JSON in a way that doesn't fit what ES5.6 expects:

[DEPRECATION] 299 Elasticsearch-5.6.10-b727a60 "Expected a boolean [true/false] for property [onloan] but got [0]"

**Comment by phochste** [comment]
Can you provide an example of the MARC to JSON mapping you are creating?

**Comment by nics** [comment]
closing this ticket
