### ISSUE TITLE
CQL query with wildcards translated to an invalid Elasticsearch query

### ISSUE THREAD

**Issue by snorri** [LibreCat/Catmandu-Store-Elasticsearch#24]
When you combine ':' with wildcards * or ?

Example:
`title = "Communication: Develop* new theories"
`
results in "Failed to parse query" error.

Cannot parse 'mainTitle:Communication:\ Develop*\ new\ theories': Encountered " ":" ": "" at line 1, column 23...

**Comment by nics** [comment]
fixed in release 1.01
