### ISSUE TITLE
Fails to work with an external ES server

### ISSUE THREAD

**Issue by eythian** [LibreCat/Catmandu-Store-Elasticsearch#6]
I'm passing this to 'new':

    0  HASH(0x3f9dd78)
       'index_name' => 'koha_robin_biblios'
       'servers' => ARRAY(0x1d90be8)
          0  'koha-es:9200'

however, the connection fails with:

[NoNodes] ** No nodes are available: [http://localhost:9200], called from sub Search::Elasticsearch::Transport::try {...}  at /usr/share/perl5/Try/Tiny.pm line 81.

This worked with an older version (0.0206), updating C::S::ES to 0.0304 causes this same call to fail.

**Comment by nics** [comment]
Hello Robin,

i think they changed the parameter to 'nodes' in Search::Elasticsearch.

Regards,
Nicolas

**Comment by eythian** [comment]
I would have spent ages figuring that one out. Confirmed that it works, thanks.

**Comment by jorol** [comment]
Hi,

could you give me an example how to connect to an external ES server via CLI?

Thanks

**Comment by jorol** [comment]
To connect to a single node you can use:

```terminal
catmandu count ElasticSearch --index_name my_index --nodes x.x.x.x:9200
```
