### ISSUE TITLE
POD incomplete for Catmandu::Store::Elasticsearch::Bag

### ISSUE THREAD

**Issue by 5p4m** [LibreCat/Catmandu-Store-Elasticsearch#9]
I would like to package this for Debian as we use it in Koha. Lintian complains about missing man pages for Catmandu::Store::Elasticsearch::Bag, which AFAICS are generated from POD. POD only has "See also"here,  which apparently is not enough.

**Comment by nics** [comment]
Hi, the new release 0.0501 has minimal but valid POD for all packages.
